resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 25m
    memory: 128Mi

service:
  enabled: false

deploymentInitialization:
  enabled: false

lifecycle:
  enabled: false

database:
  engine: null

repo: github-inventory
instance: prod

image:
  repository: gcr.io/uwit-mci-axdd/github-inventory
  tag: IMAGE_TAG

gcsCredentials:
  mounted: true
  secretName: github-inventory.axdd.s.uw.edu-gcs-credentials

cronjob:
  enabled: true
  jobs:
    - name: update-inventory
      schedule: "5 15-23 * * 1-5"
      command: ["/scripts/run.sh"]
      args: ["/app/update_github_sheet.py"]

environmentVariables:
  - name: "ENV"
    value: "prod"

externalSecrets:
  enabled: true
  secrets:
    - name: github-inventory.axdd.s.uw.edu-secrets
      externalKey: axdd/kv/data/github-inventory/secrets
      data:
        - name: github-token
          property: github-token
        - name: google-sheet-id
          property: google-sheet-id
    - name: github-inventory.axdd.s.uw.edu-gcs-credentials
      externalKey: axdd/kv/data/github-inventory/gcs-credentials
      data:
        - name: credentials.json
          property: credentials.json
environmentVariablesSecrets:
  githubToken:
    name: GITHUB_TOKEN
    secretName: github-inventory.axdd.s.uw.edu-secrets
    secretKey: github-token
  googleSheetID:
    name: GOOGLE_SHEET_ID
    secretName: github-inventory.axdd.s.uw.edu-secrets
    secretKey: google-sheet-id
